### ISSUE TITLE
chimp 0.51 does not work with meteor 1.6.1 (Babel 7)

### ISSUE THREAD

**Issue by samhatoum** [TheBrainFamily/chimpy#107]
<a href="https://github.com/teknologist"><img src="https://avatars0.githubusercontent.com/u/148448?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [teknologist](https://github.com/teknologist)**
_Tuesday Jan 30, 2018 at 21:43 GMT_
_Originally opened as https://github.com/xolvio/chimp/issues/677_

----

#####  Expected behaviour

chimp runs and processes all tests

#####  Actual behaviour

Immediate error:

```
Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...
selenium-standalone installation [=                   ] 4% 446.7s/usr/local/lib/node_modules/chimp/dist/lib/mocha/mocha-wrapper.js:75
    throw e;
    ^

TypeError: Cannot read property 'loose' of undefined
```

##### Exact steps to reproduce / repository that demonstrates the problem

Just run chimp as usual

Pretty sure this has to do with Meteor's upgrade to babel 7

#####  Version & tools:
Meteor 1.6.1

* Chimp command line used: *The exact command you used*

`chimp --mocha  --chai --ddp=http://localhost:17303 --path=tests --browser=chrome`

* Chimp config file: *Please provide a Gist if you use a config file*

default config for chimp.

My meteor .babelrc:

```

`{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "targets": {
          "browsers": ["last 2 versions", "safari >= 7", "ie 10", "not ie <= 9"]
        }
      }
    ],
    "meteor",
    "@babel/preset-react",
    "flow"
  ],
  "plugins": [
    "@babel/plugin-proposal-decorators",
    "add-react-displayname",
    ["lodash", { "id": ["lodash", "semantic-ui-react"] }],
    "@babel/plugin-proposal-class-properties"
  ],
  "env": {
    "dev": {
      "plugins": ["flow-react-proptypes"]
    }
  }
}`
```

* Chimp: *type `chimp -v`*
0.51
* Node.js: *type `node -v`*
8.9.4
* Java: *type `java -version`*
java version "1.8.0_121"
* Operation system: *type `uname -v`*
Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
and
Debian 9
#####  Console / Log Output

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
<a href="https://github.com/philcruz"><img src="https://avatars1.githubusercontent.com/u/281846?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philcruz](https://github.com/philcruz)**
_Tuesday Jan 30, 2018 at 22:39 GMT_

----

I am also having a problem running chimp 0.51 after upgrade to meteor 1.6.1

I run meteor in full test mode with 
`meteor test --full-app --driver-package tmeasday:acceptance-test-driver --settings config/config.json`

in another terminal I run chimp with
`chimp config/chimp.js --ddp=http://localhost:3000  --mocha --path=tests`

```
Chimp version:  0.51.0
ChromeDriver version:  ChromeDriver 2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e)
Java version:  java version "1.8.0_92", Java(TM) SE Runtime Environment (build 1.8.0_92-b14), Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
Selenium version:  3.4.0
Selenium drivers version:  chrome: 2.29, ie: 3.0.0, firefox: 0.19.1
OS version:  Darwin 16.7.0
Node version:  v8.9.4
Browser version:  chrome 63.0.3239.132
```

Chrome launches but it just blank. The terminal output says:  "Error: Timeout of 90000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves."

npm logs https://www.screencast.com/t/EmW4ZAIa2

**Comment by samhatoum** [comment]
<a href="https://github.com/teknologist"><img src="https://avatars0.githubusercontent.com/u/148448?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [teknologist](https://github.com/teknologist)**
_Wednesday Jan 31, 2018 at 14:13 GMT_

----

@philcruz Do you have a .babelrc in your project ?

**Comment by samhatoum** [comment]
<a href="https://github.com/teknologist"><img src="https://avatars0.githubusercontent.com/u/148448?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [teknologist](https://github.com/teknologist)**
_Wednesday Jan 31, 2018 at 14:45 GMT_

----

Ok, removing .babelrc from my meteor project fixes the issue.

So until this is fixed I will just temporarily remove .babelrc prior to running my chimp tests on CI...

Maybe there should be a way to run chimp, ignoring local .babelrc,  with something like babels --no-babelrc

**Comment by samhatoum** [comment]
<a href="https://github.com/philcruz"><img src="https://avatars1.githubusercontent.com/u/281846?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philcruz](https://github.com/philcruz)**
_Wednesday Jan 31, 2018 at 17:09 GMT_

----

@teknologist No, I don't have a .babelrc in my project.

**Comment by samhatoum** [comment]
<a href="https://github.com/d1sco"><img src="https://avatars1.githubusercontent.com/u/24909723?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [d1sco](https://github.com/d1sco)**
_Friday Feb 09, 2018 at 06:27 GMT_

----

Having this problem myself with no .babelrc in my package.json

**Comment by samhatoum** [comment]
<a href="https://github.com/Ziinc"><img src="https://avatars2.githubusercontent.com/u/22714384?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Ziinc](https://github.com/Ziinc)**
_Friday Mar 16, 2018 at 16:43 GMT_

----

@philcruz  try to run chimp with  `--debug` and `--mochaTimeout=120000`. You should be able to see the underlying reason why you're getting that error.

**Comment by samhatoum** [comment]
<a href="https://github.com/philcruz"><img src="https://avatars1.githubusercontent.com/u/281846?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philcruz](https://github.com/philcruz)**
_Wednesday Mar 28, 2018 at 15:32 GMT_

----

I switched to using a fork of practicalmeteor:mocha, cultofcoders:mocha as discussed https://github.com/practicalmeteor/meteor-mocha/issues/100 Now my tests are running again.

**Comment by bmanturner** [comment]
This is also an issue for my team:

```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/brendanturner/dev/genesis/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/brendanturner/dev/genesis/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/brendanturner/dev/genesis/node_modules/@babel/plugin-proposal-decorators/lib/index.js:35:7)
    at /Users/brendanturner/dev/genesis/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/brendanturner/dev/genesis/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/brendanturner/dev/genesis/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/brendanturner/dev/genesis/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/brendanturner/dev/genesis/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/brendanturner/dev/genesis/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
```

**Comment by abecks** [comment]
I am also experiencing this issue with Meteor 1.8:

`Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.`

Is this not because chimpy still uses the old Babel 6 packages?

```
    "babel-core": "^6.4.5",
    "babel-plugin-transform-runtime": "6.x.x",
    "babel-polyfill": "^6.3.14",
    "babel-preset-es2015": "6.x.x",
    "babel-preset-stage-2": "6.x.x",
    "babel-register": "^6.4.3",
    "babel-runtime": "6.x.x",
```

**Comment by chrisvoo** [comment]
Hi there,
I see that [4 months ago your Babel dependencies were upgraded ](https://github.com/TheBrainFamily/chimpy/blob/master/package.json)but NPM still has the old version. Will it be published the current codebase? NPM reports that the last version is `0.54.0` while in this repo I can see just `0.52.0`, which seems upgraded than the corresponding version on NPM.

**Comment by lgandecki** [comment]
Hey @chrisvoo yes, our bad. We've been crazily swamped with work recently here at TheBrain Software House. I asked @lucetius to spend some time on chimp over the next week, so all the most immediate and important issues will be taken care of.

**Comment by chrisvoo** [comment]
> Hey @chrisvoo yes, our bad. We've been crazily swamped with work recently here at TheBrain Software House. I asked @lucetius to spend some time on chimp over the next week, so all the most immediate and important issues will be taken care of.

No worries, at the moment I'm directly using this repo as GIT submodule. Thanks for the reply

**Comment by jboydensfdc** [comment]
@lucetius @lgandecki any updates on getting a new version published to npm?
