### ISSUE TITLE
Make chimp work with JDK10

### ISSUE THREAD

**Issue by samhatoum** [TheBrainFamily/chimpy#120]
<a href="https://github.com/joscha"><img src="https://avatars3.githubusercontent.com/u/188038?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [joscha](https://github.com/joscha)**
_Monday Jul 02, 2018 at 01:37 GMT_
_Originally opened as https://github.com/xolvio/chimp/pull/696_

----

Fixes:
```
{ Error: Cannot define class using reflection
    at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
    at Request.self.callback (node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at Request.<anonymous> (node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  details: undefined,
  message: 'Cannot define class using reflection',
  type: 'RuntimeError',
  seleniumStack:
   { type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'Cannot define class using reflection' } }
Error: Cannot define class using reflection
    at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
    at Request.self.callback (node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at Request.<anonymous> (node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at Request.emit (domain.js:422:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:422:20)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```
due to JDK 10.

See https://github.com/vvo/selenium-standalone/issues/369 and https://github.com/vvo/selenium-standalone/pull/371 and https://github.com/webdriverio/wdio-selenium-standalone-service/issues/47

----

_**[joscha](https://github.com/joscha)** included the following code: https://github.com/xolvio/chimp/pull/696/commits_

**Comment by samhatoum** [comment]
<a href="https://github.com/joscha"><img src="https://avatars3.githubusercontent.com/u/188038?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joscha](https://github.com/joscha)**
_Monday Jul 02, 2018 at 01:39 GMT_

----

cc @serceman

**Comment by samhatoum** [comment]
<a href="https://github.com/joscha"><img src="https://avatars3.githubusercontent.com/u/188038?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joscha](https://github.com/joscha)**
_Monday Jul 02, 2018 at 02:15 GMT_

----

CI errors do not seem to be related:
```
ExpectationFailed: Expected 'The world’s leading software development platform · GitHub' to equal 'The world's leading software development platform · GitHub'.
```
?

**Comment by samhatoum** [comment]
<a href="https://github.com/joscha"><img src="https://avatars3.githubusercontent.com/u/188038?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joscha](https://github.com/joscha)**
_Wednesday Jul 11, 2018 at 05:06 GMT_

----

@samhatoum any chance to get this in?

**Comment by samhatoum** [comment]
<a href="https://github.com/joscha"><img src="https://avatars3.githubusercontent.com/u/188038?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joscha](https://github.com/joscha)**
_Friday Jul 20, 2018 at 04:42 GMT_

----

@samhatoum is chimp still maintained?

**Comment by joscha** [comment]
@lgandecki any chance to get https://github.com/xolvio/chimp/pull/696 integrated?

**Comment by lgandecki** [comment]
yup. @lucetius want to take a look ? :)
