### ISSUE TITLE
Adding chimpy as dev-dependency breaks app

### ISSUE THREAD

**Issue by schlaegerz** [TheBrainFamily/chimpy#150]
##### Exact steps to reproduce / repository that demonstrates the problem
When I have chimpy installed as a devdependency my server crashes when I run it in not test mode.

#####  Console / Log Output
W20191004-11:10:07.047(-7)? (STDERR) /.meteor/packages/meteor-tool/.1.8.0_2.5gk8rs.jxa3o++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20191004-11:10:07.106(-7)? (STDERR) 						throw(ex);
W20191004-11:10:07.106(-7)? (STDERR) 						^
W20191004-11:10:07.107(-7)? (STDERR) 
W20191004-11:10:07.107(-7)? (STDERR) AssertionError [ERR_ASSERTION]: Cannot await unless Promise.Fiber is defined
W20191004-11:10:07.108(-7)? (STDERR)     at awaitPromise (/Users/zacholigschlaeger/.meteor/packages/promise/.0.11.2.1ixw4hn.8uhlk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:68:12)
W20191004-11:10:07.108(-7)? (STDERR)     at Promise.await (/Users/zacholigschlaeger/.meteor/packages/promise/.0.11.2.1ixw4hn.8uhlk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
W20191004-11:10:07.108(-7)? (STDERR)     at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1091:12)
W20191004-11:10:07.109(-7)? (STDERR)     at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1105:22)
W20191004-11:10:07.109(-7)? (STDERR)     at SynchronousCursor.map (packages/mongo/mongo_driver.js:1115:10)
W20191004-11:10:07.109(-7)? (STDERR)     at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1139:17)
W20191004-11:10:07.109(-7)? (STDERR)     at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:887:44)
W20191004-11:10:07.110(-7)? (STDERR)     at MongoConnection.findOne (packages/mongo/mongo_driver.js:794:56)
W20191004-11:10:07.111(-7)? (STDERR)     at OplogHandle._startTailing (packages/mongo/oplog_tailing.js:228:57)
W20191004-11:10:07.112(-7)? (STDERR)     at new OplogHandle (packages/mongo/oplog_tailing.js:82:8)
W20191004-11:10:07.112(-7)? (STDERR)     at new MongoConnection (packages/mongo/mongo_driver.js:225:25)
W20191004-11:10:07.112(-7)? (STDERR)     at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
W20191004-11:10:07.113(-7)? (STDERR)     at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
W20191004-11:10:07.114(-7)? (STDERR)     at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
W20191004-11:10:07.115(-7)? (STDERR)     at new Collection (packages/mongo/collection.js:97:40)
W20191004-11:10:07.115(-7)? (STDERR)     at new AccountsCommon (packages/accounts-base/accounts_common.js:23:18)

**Comment by lgandecki** [comment]
well, that's not good.. Any chance you could try to prepare a small reproduction? Maybe just having the same version of Meteor + accounts woud do the trick?

**Comment by bmanturner** [comment]
This is due to the inclusion of fibers in this package. I don't know why, but I've traced it to that dependency
