### ISSUE TITLE
waitUntil does not log a useful stacktrace

### ISSUE THREAD

**Issue by samhatoum** [TheBrainFamily/chimpy#54]
<a href="https://github.com/acthp"><img src="https://avatars3.githubusercontent.com/u/494506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [acthp](https://github.com/acthp)**
_Wednesday Oct 05, 2016 at 00:34 GMT_
_Originally opened as https://github.com/xolvio/chimp/issues/484_

----

Before you ask, I've already opened an issue with webdriverio, who claim this is a chimp problem.

https://github.com/webdriverio/webdriverio/issues/1629
##### Expected behaviour

An exception in a waitUntil condition should log the stacktrace of the error.
##### Actual behaviour

A stacktrace into fiber / future code is logged.
##### Steps to reproduce the problem

Throw an error in a waitUntil condition.
##### Used version
- Chimp:  0.41.1
- Node.js: 4.0.0
- Operation system: ubuntu
##### Console / Log Output

```
 Error: Promise was rejected with the following reason: TypeError: undefined is not a function
  at Object.Future.wait (node_modules/fibers/future.js:449:15)
  at Object.<anonymous> (node_modules/wdio-sync/build/index.js:345:27)
  at Context.<anonymous> (test/chimp/test.js:110:12)
  at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
```

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by samhatoum** [comment]
<a href="https://github.com/lucetius"><img src="https://avatars2.githubusercontent.com/u/3426608?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lucetius](https://github.com/lucetius)**
_Tuesday Oct 11, 2016 at 07:10 GMT_

----

Please provide us detailed steps to reproduce the error.

**Comment by samhatoum** [comment]
<a href="https://github.com/lgandecki"><img src="https://avatars1.githubusercontent.com/u/4002543?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lgandecki](https://github.com/lgandecki)**
_Friday Nov 18, 2016 at 21:32 GMT_

----

"Throw an error in a waitUntil condition."
I think this is enough for us to reproduce, thanks for submitting, we will take a look at this shortly!
