### ISSUE TITLE
The best matching driver provider org.openqa.selenium.edge.EdgeDriver

### ISSUE THREAD

**Issue by samhatoum** [TheBrainFamily/chimpy#55]
<a href="https://github.com/SindhuGupta"><img src="https://avatars1.githubusercontent.com/u/13119016?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SindhuGupta](https://github.com/SindhuGupta)**
_Thursday Oct 06, 2016 at 10:28 GMT_
_Originally opened as https://github.com/xolvio/chimp/issues/486_

----

Hello,

I am facing the below error for safari browser. I am trying to run protractor tests on safari browser.

Please find the details below:
E/launcher - The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't create a new driver instance for Capabilities [{count=1, browserName=safari}]
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'BLRL36257', ip: '172.22.240.106', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_17'
Driver info: driver.version: unknown

Here is my config:

multiCapabilities: [
{
browserName: 'safari'
}
]

Please provide solution.

Thanks,
Sindhu

**Comment by samhatoum** [comment]
<a href="https://github.com/samhatoum"><img src="https://avatars2.githubusercontent.com/u/2021955?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [samhatoum](https://github.com/samhatoum)**
_Saturday Dec 17, 2016 at 01:20 GMT_

----

where did you get `multiCapabilities` from?

**Comment by samhatoum** [comment]
<a href="https://github.com/Siva123Prasad"><img src="https://avatars0.githubusercontent.com/u/23262286?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Siva123Prasad](https://github.com/Siva123Prasad)**
_Thursday Jun 28, 2018 at 09:14 GMT_

----

Even I have the same issue. 

Trying to run my tests through protractor. Getting this error

The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{count=1, browserName=Chrome}]
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'krishnas.local', ip: '192.168.50.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '1.8.0_131'
Driver info: driver.version: unknown
[14:18:20] E/launcher - WebDriverError: The best matching driver provider org.openqa.selenium.safari.SafariDriver can't create a new driver instance for Capabilities [{count=1, browserName=Chrome}]
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'krishnas.local', ip: '192.168.50.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '1.8.0_131'
Driver info: driver.version: unknown

I have the capabilities like this :

capabilities: {
    'browserName': 'Chrome',
  },


Update: I have re-installed protractor and Webdriver-manager. 
The error looks like this now.

E/launcher - Unable to create session from {
  "desiredCapabilities": {
    "count": 1,
    "browserName": "Chrome"
  },
  "capabilities": {
    "desiredCapabilities": {
      "browserName": "Chrome",
      "count": 1
    },
    "firstMatch": [
      {
        "browserName": "Chrome"
      }
    ]
  }
}
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'krishnas.local', ip: 'fe80:0:0:0:1c69:4717:69fe:bbd%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '1.8.0_131'
Driver info: driver.version: unknown
[15:47:20] E/launcher - SessionNotCreatedError: Unable to create session from {
  "desiredCapabilities": {
    "count": 1,
    "browserName": "Chrome"
  },
  "capabilities": {
    "desiredCapabilities": {
      "browserName": "Chrome",
      "count": 1
    },
    "firstMatch": [
      {
        "browserName": "Chrome"
      }
    ]
  }
}
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
System info: host: 'krishnas.local', ip: 'fe80:0:0:0:1c69:4717:69fe:bbd%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.2', java.version: '1.8.0_131'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at createDriver (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:635:14)
    at Local.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/usr/local/lib/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:604:44
