### ISSUE TITLE
server.execute throws "Can't wait without a Fiber"

### ISSUE THREAD

**Issue by samhatoum** [TheBrainFamily/chimpy#56]
<a href="https://github.com/thiagodelgado111"><img src="https://avatars3.githubusercontent.com/u/1891013?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thiagodelgado111](https://github.com/thiagodelgado111)**
_Thursday Oct 06, 2016 at 19:01 GMT_
_Originally opened as https://github.com/xolvio/chimp/issues/490_

----

[UPDATE]  - Added a better error message
##### Expected behaviour

Runs code in Meteor context and the scenario passes

```
module.exports = function () {
  this.Given(/^something exists$/, async function () {
    const countThings = await this.countAllTheThings();

    server.execute(addRecord, 'text');

    function addRecord (text) {
      const MyCollection = require('meteor/mycollection');
      MyCollection.insert({ title: text });
    }
  });
};
```
##### Actual behaviour

The scenario fails and an error message is logged on the console:
##### Used version
- Chimp: 0.40.6
- Node.js: v5.5
- Operation system: 

ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G1004
##### Console / Log Output

```
Message:
>> [chimp] Detected an unhandledRejection:
>> [chimp][hooks] Error: Can't wait without a fiber
       at Function.wait (/Users/thiagodelgado/.nvm/versions/node/v5.5.0/lib/node_modules/chimp/node_modules/fibers/future.js:159:9)
       at Object.Future.wait (/Users/thiagodelgado/.nvm/versions/node/v5.5.0/lib/node_modules/chimp/node_modules/fibers/future.js:448:10)
       at Object.<anonymous> (/Users/thiagodelgado/.nvm/versions/node/v5.5.0/lib/node_modules/chimp/node_modules/xolvio-fiber-utils/index.js:48:19)
         at Object.global.ddp.execute (/Users/thiagodelgado/.nvm/versions/node/v5.5.0/lib/node_modules/chimp/dist/lib/chimp-helper.js:171:27)
         at World._callee$ (features/step_definitions/common/Given_a_thing_is_counted.js:18:12)
         at nextTickCallbackWith0Args (node.js:452:9)
         at process._tickCallback (node.js:381:13)
```

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by samhatoum** [comment]
<a href="https://github.com/samhatoum"><img src="https://avatars2.githubusercontent.com/u/2021955?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [samhatoum](https://github.com/samhatoum)**
_Saturday Dec 17, 2016 at 01:23 GMT_

----

Could you put this in a repro for us please? Difficult to see what's happening from just the code above
