### ISSUE TITLE
Test hangs if some actions with non-existent element performed

### ISSUE THREAD

**Issue by samhatoum** [TheBrainFamily/chimpy#67]
<a href="https://github.com/faizrr"><img src="https://avatars0.githubusercontent.com/u/4959660?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [faizrr](https://github.com/faizrr)**
_Wednesday Jan 25, 2017 at 14:54 GMT_
_Originally opened as https://github.com/xolvio/chimp/issues/564_

----

When I use chromedriver and perform `browser.element()` for non-existent element selector, test hangs on the step where it was mentioned and other steps don't perform.

Also, this problem doesn't occur on phantomjs.

Also, I tried to run similar test on plain webdriver.io and I couldn't experience such error.

Here's the test:
```javascript
describe('Test', () => {
  before(() => {
    browser.url('http://google.com')
  })

  it('test one', () => {
    const element = browser.element('foo')
    expect(element.isExisting()).to.be.false
  })

  it('test two', () => {
    const element = browser.element('body')
    expect(element.isExisting()).to.be.true
  })
})
```

#####  Expected behaviour

```
Test
    ✓ test one
    ✓ test two


  2 passing (2s)
```

#####  Actual behaviour
```
  Test
    1) test one
    2) test two


  0 passing (11s)
  2 failing

  1) Test test one:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) Test test two:
     TypeError: element.isExisting is not a function
      at Context.<anonymous> (tests/feature/desktop/simple.js:13:20)
      at node_modules/chimp/dist/lib/utils/fiberize.js:25:14
```

##### Exact steps to reproduce / repository that demonstrates the problem
Here's the config for chimp:
```javascript
{
  browser: 'chrome',
  mocha: true,
  mochaConfig: {
    timeout: 10000
  },
  watch: true
}
```

Log if chrome is used: https://gist.github.com/faizrr/e8123c67d1e0033eba15e62cbb46ea9b
Log if phantomjs is used: https://gist.github.com/faizrr/c8470f5227a2c36fb3289348fbb268c6

#####  Version & tools:

* Chimp: 0.45.1
* Node.js: 6.7.0
* Java: 1.8.0_101
* Operation system: macOS 10.12.2

**Comment by samhatoum** [comment]
<a href="https://github.com/faizrr"><img src="https://avatars0.githubusercontent.com/u/4959660?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [faizrr](https://github.com/faizrr)**
_Tuesday Jan 31, 2017 at 13:59 GMT_

----

Found similar issue. But it was fixed. https://github.com/webdriverio/webdriverio/issues/1466

**Comment by samhatoum** [comment]
<a href="https://github.com/lucetius"><img src="https://avatars2.githubusercontent.com/u/3426608?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lucetius](https://github.com/lucetius)**
_Friday Mar 10, 2017 at 10:26 GMT_

----

We can't reproduce the issue. Try to run newest Chimp version. You can also try to remove `browser` from your config file. This way you will be using Chromedriver directly without Java.
Also when you use watch mode in Chimp don't forget to add `@watch` or `@focus` in your tests.
